Name = "user"
# dev | test | prod
Env = "dev"

[dev]
debug = true
ConfigTemplateDir = "_example/config"
NoInject = []
[dev.LocalConfig]
Paths = ["_example/config/local.toml"]
ReloadInterval = "10s"

[test]
Debug = false
NoInject = ["Apollo","Etcd", "Es"]

[test.LocalConfig]
Paths = ["_example/config/local.test.toml"]
ReloadInterval = "10s"

[test.ConfigCenter]
Format = "json"
Type = "nacos"

[test.ConfigCenter.nacos]
DataId = "pro"
Group = "DEFAULT_GROUP"

[[test.ConfigCenter.nacos.ServerConfigs]]
Scheme = "http"
IpAddr = "localhost"
Port = 9000
GrpcPort = 10000

[test.ConfigCenter.nacos.ClientConfig]
NamespaceId = ""
username = "nacos"
password = "123456"
LogLevel = "debug"

[prod]
Debug = false
[prod.ConfigCenter.http]
Interval = 100
Url = "http://localhost:6666/local.toml"