[Customize]
Bool = false
Duration = 86400000000000
Float = 0.0
Int = 0
String = ''

[Log]
CallerKey = ''
ConsoleSeparator = ''
Development = false
DisableCaller = false
DisableStacktrace = false
EncodeLevelType = ''
FunctionKey = ''
Level = 'info'
LevelKey = ''
LineEnding = ''
MessageKey = ''
Name = ''
NameKey = ''
SkipLineEnding = false
StacktraceKey = ''
TimeKey = ''
TimeLayout = ''

[[Log.ErrorOutputPaths]]

[Log.OutputPaths]
[[Log.OutputPaths.Console]]

[[Log.OutputPaths.Json]]

[Log.Sampling]
Initial = 0
Thereafter = 0

[Mqtt]
AutoAckDisabled = false
AutoReconnect = false
CAFile = ''
CleanSession = false
ClientID = ''
ConnectRetry = false
ConnectRetryInterval = 0
ConnectTimeout = 0
KeepAlive = 0
MaxReconnectInterval = 0
MaxResumePubInFlight = 0
MessageChannelDepth = 0
Order = false
Password = ''
PingTimeout = 0
ProtocolVersion = 0
ResumeSubs = false
ServerName = ''
Username = ''
WillEnabled = false
WillQos = 0
WillRetained = false
WillTopic = ''
WriteTimeout = 0

[[Mqtt.Brokers]]

[Mqtt.Dialer]
DualStack = false
FallbackDelay = 0
KeepAlive = 0
Timeout = 0

[Mqtt.Dialer.KeepAliveConfig]
Count = 0
Enable = false
Idle = 0
Interval = 0

[Mqtt.Dialer.Resolver]
PreferGo = false
StrictErrors = false

[[Mqtt.Servers]]
ForceQuery = false
Fragment = ''
Host = ''
OmitHost = false
Opaque = ''
Path = ''
RawFragment = ''
RawPath = ''
RawQuery = ''
Scheme = ''

[Mqtt.WebsocketOptions]
ReadBufferSize = 0
WriteBufferSize = 0

[[Mqtt.WillPayload]]
